name: Contirbutor requests review - Check payment

on:
  pull_request_target:
    types: [review_requested]

permissions:
  issues: write
  pull-requests: write

jobs:
  demo_qr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install qrcode

      - name: Run qr_code.py
        id: run_qr_script
        run: |
          python .github/scripts/qr_code.py

      - name: Upload QR code as artifact
        uses: actions/upload-artifact@v2
        with:
          name: qr-code
          path: qr_code.png

      - name: Download QR code artifact
        uses: actions/download-artifact@v2
        with:
          name: qr-code

      - name: Get artifact URL
        id: artifact_url
        run: |
          curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            https://api.github.com/repos/${{ github.repository }}/actions/artifacts \
            | jq -r '.artifacts[0].archive_download_url' \
            | echo "::set-output name=url::$(cat -)"

        # run: echo "::set-output name=url::$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" https://api.github.com/repos/${{ github.repository }}/actions/artifacts | jq -r '.artifacts[0].archive_download_url')"

      - name: Put artifact QR url in PR thread
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `![QR Code](${{ steps.artifact_url.outputs.url }})`
            github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: output,
              });

  check_that_payment:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Confirmation
        run: echo "review requested or review removed"

      - name: Check payment Endpoint
        env:
          INVOICE_KEY: ${{ secrets.INVOICE_KEY_1 }}
        id: check_payment
        run: |
          checking_id="d810916c125b1eb8b25c9133e2d32c5997ce3094e9f4216982180e02f58e06e2"
          response=$(curl -s -X GET \
              -H "X-Api-Key: $INVOICE_KEY" \
              -H "Content-Type: application/json" \
              https://d5aedbf627.d.voltageapp.io/api/v1/payments/$checking_id)
          echo "Server response:"
          echo "$response"

          # get is_paid which is bool
          is_paid=$(echo "$response" | jq -r '.paid')
          echo "payment_request: $payment_request"

          # Use the extracted value in the next step
          echo "::set-output name=is_paid::$is_paid"

      - name: Handle Payment Status
        if: steps.check_payment.outputs.is_paid == 'true'
        run: |
          echo "Payment is confirmed. Proceeding with the review request."

      - name: Contrib HAS paid
        if: steps.check_payment.outputs.is_paid == 'true'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const message = `Payment has been recieved, sit tight, running openai query`;
            github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: message
              });

      - name: Contrib has NOT paid
        if: steps.check_payment.outputs.is_paid == 'false'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const message = `You haven't paid yet bro; close then re-open the review request`;
            github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: message
              });

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print diff
        id: get_diff
        uses: actions/github-script@v7
        with:
          script: |
            const diff_url = context.payload.pull_request.diff_url
            const result = await github.request(diff_url)
            console.log(result)
            core.setOutput('diff', result.data)
            

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Run get_completion.py
        id: openai_request
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          PR_DIFF: ${{ steps.get_diff.outputs.diff }}
        run: |
          python scripts/get_completion.py

      - name: Use completion output
        run: |
          echo "Completion output: ${{ steps.openai_request.outputs.completion_output }}"

      - name: Put completion into PR thread
        # if: steps.check_payment.outputs.is_paid == 'true'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `${{ steps.openai_request.outputs.completion_output }}`;
            const escapedOutput = output.replace(/`/g, '\\`').replace(/\\n/g, '\n');
            github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: escapedOutput
              });
